Hope I did this correctly
k3live/magento2-woopra pull request #6
Opened 2019-09-20 13:23 UTC by mrlerch

This is the first time contributing so please excuse if I did something wrong. I have been in contact with William at Woopra and he told me that his developers didn't have the resources to make this change, but I needed this to be compatible with PHP 7.1+ and 7.2+

Also there is an issue with the composer instructions, and I fixed that too in the Readme.

Again, if I did this wrong I am sorry. Just trying to fix incompatibility.

2019-09-20 22:02 UTC, jad939933 approved these changes

2019-09-20 22:02 UTC, jad939933 approved these changes

2019-09-26 06:55 UTC, kmcgregor requested changes
composer on github needs to remain on /k3live. If you are pulling from Magento then you would need /woopra.

2019-09-26 19:17 UTC, mrlerch commented
This one (see screen shot).

It was updated already 4 days ago and merged, yet still same problem. Or is there yet another repo?



Martin R. Lerch
--------------------------------
  mrlerch@gmail.com
   702.321.0908




> On Sep 25, 2019, at 11:55 PM, Kevin M. <notifications@github.com> wrote:
> 
> @kmcgregor requested changes on this pull request.
> 
> composer on github needs to remain on /k3live. If you are pulling from Magento then you would need /woopra.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/k3live/magento2-woopra/pull/6?email_source=notifications&email_token=AC7L2GMLDRVZW2FW3ROVF7LQLRMETA5CNFSM4IYXBBT2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCF7LJ6A#pullrequestreview-293516536>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AC7L2GLD6HAWEOG4VKNTYBTQLRMETANCNFSM4IYXBBTQ>.
>

2019-10-31 18:07 UTC, mrlerch commented
Hello. There are still 3 pending requests. Please advise.

https://github.com/Woopra/magento2-woopra/pulls

Martin R. Lerch
--------------------------------
  mrlerch@gmail.com
   702.321.0908




> On Sep 25, 2019, at 11:55 PM, Kevin M. <notifications@github.com> wrote:
> 
> @kmcgregor requested changes on this pull request.
> 
> composer on github needs to remain on /k3live. If you are pulling from Magento then you would need /woopra.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/k3live/magento2-woopra/pull/6?email_source=notifications&email_token=AC7L2GMLDRVZW2FW3ROVF7LQLRMETA5CNFSM4IYXBBT2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCF7LJ6A#pullrequestreview-293516536>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AC7L2GLD6HAWEOG4VKNTYBTQLRMETANCNFSM4IYXBBTQ>.
>

2019-11-02 05:47 UTC, merged